### ISSUE TITLE
How to inject noise into the supervisor’s policy while demonstrating?

### ISSUE THREAD

**Issue by xiao-dong** [BerkeleyAutomation/DART#4]
I try my best to understand the paper but I could not find how to inject noise into the supervisor’s policy while demonstrating in a real robot. Could you please tell me when to add noise and how to add noise?
 Thanks a lot.

**Comment by jon--lee** [comment]
Hi! One way to do it on a continuous control robot is to start with the control that the supervisor intends to send to the robot in the form of a vector, for example u = [1, 1], and then get a random sample from a normal/gaussian distribution, for example v =  np.random.multivariate_normal(np.zerso(2), cov), where cov is the covariance matrix computed from DART or something you choose. Then instead of sending u to the robot, you can send u + v, which makes u noisy. You can think of it as intercepting the supervisor's intended control, modifying it, and then passing the modified version on to the robot.
